name = "gbr_md_lustre"
version = "1.0.0"
target = "javascript"

description = "Ⓜ️ Gleam library convert markdown to lustre elements"
licences = ["Apache-2.0"]
repository = { type = "github", user = "gleam-br", repo = "gbr_md_lustre" }
links = []

[dependencies]
mork = "~> 1.11"
lustre = "~> 5.5"
gleam_stdlib = "~> 0.68"

[dev-dependencies]
gleeunit = "~> 1.9"
